{
 "title": "AWS Kafka Cluster",
 "description": "https://docs.aws.amazon.com/msk/latest/developerguide/monitoring.html",
 "tags": [
  "AWS",
  "Kafka",
  "Amazon",
  "CloudWatch"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "mskclustername",
    "label": "Cluster Name",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec, Cluster Name)"
   },
   {
    "name": "brokerid",
    "label": "Broker ID",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec, Broker ID)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "dimension_values($region,AWS/Kafka, BytesInPerSec,Topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active Controller Count",
   "type": "stat",
   "description": "Only one controller per cluster should be active at any given time.\n",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "dimensions": { "Cluster Name": "$mskclustername" },
     "metricName": "ActiveControllerCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Global Partition Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$mskclustername" },
     "metricName": "GlobalPartitionCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "OfflinePartitionsCount",
   "type": "graph",
   "description": "Total number of partitions that are offline in the cluster.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$mskclustername" },
     "metricName": "OfflinePartitionsCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Global Topic Count",
   "type": "graph",
   "description": "Total number of topics across all brokers in the cluster.\n",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Cluster Name": "$mskclustername" },
     "metricName": "GlobalTopicCount",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "ZooKeeper Request Latency MsMean",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ZooKeeperRequestLatencyMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Average" ]
      }
     ]
    },
    {
     "title": "ZooKeeperSessionState\t",
     "type": "graph",
     "description": "Connection status of broker's ZooKeeper session which may be one of the following: NOT_CONNECTED: '0.0', ASSOCIATING: '0.1', CONNECTING: '0.5', CONNECTEDREADONLY: '0.8', CONNECTED: '1.0', CLOSED: '5.0', AUTH_FAILED: '10.0'.\n",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ZooKeeperSessionState",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "KafkaDataLogsDiskUsed",
     "type": "graph",
     "description": "The percentage of disk space used for data logs.\n",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "KafkaDataLogsDiskUsed",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "MemoryBuffered\t",
     "type": "graph",
     "description": "The size in bytes of buffered memory for the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "MemoryBuffered",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "KafkaAppLogsDiskUsed",
     "type": "graph",
     "description": "The percentage of disk space used for application logs.\n",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "KafkaAppLogsDiskUsed",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "MemoryUsed",
     "type": "graph",
     "description": "The size in bytes of memory that is in use for the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "MemoryUsed",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "MemoryFree",
     "type": "graph",
     "description": "The size in bytes of memory that is free and available for the broker.\n",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "MemoryFree",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "CpuIdle",
     "type": "graph",
     "description": "The percentage of CPU idle time.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "CpuIdle",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RootDiskUsed",
     "type": "graph",
     "description": "The percentage of the root disk used by the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RootDiskUsed",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "SwapFree",
     "type": "graph",
     "description": "The size in bytes of swap memory that is available for the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "SwapFree",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "SwapUsed",
     "type": "graph",
     "description": "The size in bytes of swap memory that is in use for the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "SwapUsed",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "CpuUser\t",
     "type": "graph",
     "description": "The percentage of CPU in user space.",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "CpuUser",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "MemoryCached\t",
     "type": "graph",
     "description": "The size in bytes of cached memory for the broker.",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "MemoryCached",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "CpuSystem",
     "type": "graph",
     "description": "The percentage of CPU in kernel space.",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "CpuSystem",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkTxPackets",
     "type": "graph",
     "description": "The number of packets transmitted by the broker.",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkTxPackets",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkTxErrors",
     "type": "graph",
     "description": "The number of network transmit errors for the broker.\n",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkTxErrors",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkTxDropped",
     "type": "graph",
     "description": "The number of dropped transmit packages.\n",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkTxDropped",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkRxPackets",
     "type": "graph",
     "description": "The number of packets received by the broker.",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkRxPackets",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkRxErrors",
     "type": "graph",
     "description": "The number of network receive errors for the broker.",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkRxErrors",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkRxDropped",
     "type": "graph",
     "description": "Network dropped\n",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 41 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkRxDropped",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per Broker Level Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "ReplicationBytesInPerSec",
     "type": "graph",
     "description": "The number of bytes per second received from other brokers.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ReplicationBytesInPerSec",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ReplicationBytesOutPerSec",
     "type": "graph",
     "description": "The number of bytes per second sent to other brokers.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ReplicationBytesOutPerSec",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchThrottleByteRate",
     "type": "graph",
     "description": "The number of throttled bytes per second.\n",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Cluster Name": "$mskclustername" },
       "metricName": "FetchThrottleByteRate",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchConsumerRequestQueueTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that the consumer request waits in the request queue.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchConsumerRequestQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchConsumerLocalTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that the consumer request is processed at the leader.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchConsumerLocalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchConsumerResponseSendTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds for the consumer to send a response.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchConsumerResponseSendTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchThrottleQueueSize",
     "type": "graph",
     "description": "The number of messages in the throttle queue.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchThrottleTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchConsumerResponseQueueTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that the consumer request waits in the response queue.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchConsumerResponseQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "LeaderCount",
     "type": "graph",
     "description": "The number of leader replicas.\n",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "LeaderCount",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchThrottleTime",
     "type": "graph",
     "description": "The average fetch throttle time in milliseconds.\n",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchThrottleTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "NetworkProcessorAvgIdlePercent",
     "type": "graph",
     "description": "The average percentage of the time the network processors are idle.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "NetworkProcessorAvgIdlePercent",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceRequestQueueTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that request messages spend in the queue.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$clustername" },
       "metricName": "ProduceRequestQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "PartitionCount",
     "type": "graph",
     "description": "The number of partitions for the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "PartitionCount",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceLocalTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds for the follower to send a response.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceLocalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceResponseQueueTimeMsMean\t",
     "type": "graph",
     "description": "The mean time in milliseconds that response messages spend in the queue.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceResponseQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceResponseSendTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds spent on sending response messages.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceResponseSendTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceMessageConversionsPerSec",
     "type": "graph",
     "description": "The number of produce message conversions per second for the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceMessageConversionsPerSec",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceThrottleByteRate",
     "type": "graph",
     "description": "The number of throttled bytes per second.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceThrottleByteRate",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceThrottleQueueSize",
     "type": "graph",
     "description": "The number of messages in the throttle queue.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceThrottleQueueSize",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceThrottleTime",
     "type": "graph",
     "description": "The average produce throttle time in milliseconds.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Cluster Name": "$clustername" },
       "metricName": "ProduceThrottleTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchFollowerRequestQueueTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that the follower request waits in the request queue.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchFollowerRequestQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceTotalTimeMsMean",
     "type": "graph",
     "description": "The mean produce time in milliseconds.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceTotalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "ProduceMessageConversionsTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds spent on message format conversions.\n",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "ProduceMessageConversionsTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchConsumerTotalTimeMsMean",
     "type": "graph",
     "description": "The mean total time in milliseconds that consumers spend on fetching data from the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 50 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchConsumerTotalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestHandlerAvgIdlePercent",
     "type": "graph",
     "description": "The average percentage of the time the request handler threads are idle.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RequestHandlerAvgIdlePercent",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchFollowerLocalTimeMsMean",
     "type": "graph",
     "description": "The mean time in milliseconds that the follower request is processed at the leader.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchFollowerLocalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchFollowerResponseQueueTimeMsMean\t",
     "type": "graph",
     "description": "The mean time in milliseconds that the follower request waits in the response queue.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchFollowerResponseQueueTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestTime",
     "type": "graph",
     "description": "The average time in milliseconds spent in broker network and I/O threads to process requests.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 57 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RequestTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "UnderMinIsrPartitionCount",
     "type": "graph",
     "description": "The number of under minIsr partitions for the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "UnderMinIsrPartitionCount",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestExemptFromThrottleTime",
     "type": "graph",
     "description": "The average time in milliseconds spent in broker network and I/O threads to process requests that are exempt from throttling.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RequestExemptFromThrottleTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestThrottleQueueSize",
     "type": "graph",
     "description": "The number of messages in the throttle queue.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RequestThrottleQueueSize",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchFollowerResponseSendTimeMsMean\t",
     "type": "graph",
     "description": "The mean time in milliseconds for the follower to send a response.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 64 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchFollowerResponseSendTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "UnderReplicatedPartitions",
     "type": "graph",
     "description": "The number of under-replicated partitions for the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "UnderReplicatedPartitions",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestBytesMean",
     "type": "graph",
     "description": "The mean number of request bytes for the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "RequestBytesMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "FetchFollowerTotalTimeMsMean",
     "type": "graph",
     "description": "The mean total time in milliseconds that followers spend on fetching data from the broker.",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
       "metricName": "FetchFollowerTotalTimeMsMean",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    },
    {
     "title": "RequestThrottleTime",
     "type": "graph",
     "description": "The average request throttle time in milliseconds.",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 71 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "Cluster Name": "$clustername" },
       "metricName": "RequestThrottleTime",
       "namespace": "AWS/Kafka",
       "region": "$region",
       "statistics": [ "Maximum" ]
      }
     ]
    }
   ]
  },
  {
   "title": "Per Topic Per Broker Level monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "BytesInPerSec\t",
   "type": "graph",
   "description": "The number of bytes per second received from clients.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
     "metricName": "BytesInPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "BytesOutPerSec\t",
   "type": "graph",
   "description": "The number of bytes per second sent to clients.\n",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
     "metricName": "BytesOutPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "graph",
   "description": "The number of messages received per second.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
     "metricName": "MessagesInPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "FetchMessageConversionsPerSec",
   "type": "graph",
   "description": "The number of fetch message conversions per second for the broker.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
     "metricName": "FetchMessageConversionsPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "ProduceMessageConversionsPerSec",
   "type": "graph",
   "description": "The number of conversions per second for produced messages.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "Broker ID": "$brokerid", "Cluster Name": "$mskclustername" },
     "metricName": "ProduceMessageConversionsPerSec",
     "namespace": "AWS/Kafka",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}